const { Buffer } = require('buffer');

exports.handler = async function (event, context) {
    // Handle CORS preflight
    if (event.httpMethod === 'OPTIONS') {
        return {
            statusCode: 200,
            headers: {
                'Access-Control-Allow-Origin': '*',
                'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
                'Access-Control-Allow-Headers': 'Content-Type'
            },
            body: ''
        };
    }

    if (event.httpMethod !== 'POST') {
        return {
            statusCode: 405,
            body: JSON.stringify({ error: 'Method Not Allowed' })
        };
    }

    try {
        const { pkgUrl, filename, size, userIp } = JSON.parse(event.body);

        if (!pkgUrl || !filename) {
            return {
                statusCode: 400,
                body: JSON.stringify({ error: 'Missing required parameters' })
            };
        }

        // Generate payload (this is a simplified version)
        // In reality, you'd need the actual payload binary
        const callbackPort = 9022;

        // Create metadata packet
        const generateMetadata = () => {
            const contentId = "EP0000-CUSA00000_00-0000000000000000";
            const bgftType = "gd";

            const urlData = Buffer.from(pkgUrl, "utf-8");
            const nameData = Buffer.from(filename, "utf-8");
            const idData = Buffer.from(contentId, "utf-8");
            const typeData = Buffer.from(bgftType, "utf-8");

            const packet = Buffer.alloc(
                4 + 4 + urlData.length +
                4 + nameData.length +
                4 + idData.length +
                4 + typeData.length +
                8 + 4
            );

            let o = 0;
            packet.writeUInt32LE(1, o); o += 4;
            packet.writeUInt32LE(urlData.length, o); o += 4; urlData.copy(packet, o); o += urlData.length;
            packet.writeUInt32LE(nameData.length, o); o += 4; nameData.copy(packet, o); o += nameData.length;
            packet.writeUInt32LE(idData.length, o); o += 4; idData.copy(packet, o); o += idData.length;
            packet.writeUInt32LE(typeData.length, o); o += 4; typeData.copy(packet, o); o += typeData.length;
            packet.writeBigUInt64LE(BigInt(size || 0), o); o += 8;
            packet.writeUInt32LE(0, o);

            return packet.toString('base64');
        };

        const metadata = generateMetadata();

        // Generate JavaScript payload for PS4 browser
        const jsPayload = `
// PS4 Package Installer Payload
// Generated by Web Installer

const exploit = (function() {
  'use strict';
  
  // WebRTC for IP detection (for callback server simulation)
  const getLocalIP = () => {
    return new Promise((resolve) => {
      const pc = new RTCPeerConnection({iceServers:[]});
      pc.createDataChannel('');
      pc.createOffer().then(sdp => pc.setLocalDescription(sdp));
      pc.onicecandidate = (ice) => {
        if (ice.candidate && ice.candidate.candidate) {
          const ip = /([0-9]{1,3}(\\.[0-9]{1,3}){3})/.exec(ice.candidate.candidate);
          if (ip) resolve(ip[1]);
        }
      };
      setTimeout(() => resolve('127.0.0.1'), 1000);
    });
  };
  
  // Send payload to PS4 kernel
  const sendPayload = (payload) => {
    return new Promise((resolve) => {
      try {
        // This would be actual kernel exploitation code
        // For demo, we'll simulate it
        console.log('Sending payload to kernel...');
        
        // Simulate success
        setTimeout(() => {
          console.log('Payload executed successfully!');
          resolve(true);
        }, 1000);
      } catch (e) {
        console.error('Payload execution failed:', e);
        resolve(false);
      }
    });
  };
  
  // Start installation
  const startInstallation = async (pkgUrl, filename, metadata) => {
    console.log('Starting installation...');
    console.log('Package:', filename);
    console.log('URL:', pkgUrl);
    
    // Send metadata to PS4 package installer
    const installData = {
      action: 'install',
      url: pkgUrl,
      name: filename,
      metadata: metadata
    };
    
    // Try to trigger PS4's package installer
    try {
      // Method 1: Try to open the package URL directly
      window.open(pkgUrl, '_system');
      
      // Method 2: Create a download link
      const link = document.createElement('a');
      link.href = pkgUrl;
      link.download = filename;
      link.click();
      
      // Method 3: Use PS4-specific APIs if available
      if (typeof PS4 !== 'undefined') {
        PS4.installPackage(pkgUrl, filename);
      }
      
      return true;
    } catch (e) {
      console.error('Installation failed:', e);
      return false;
    }
  };
  
  return {
    getLocalIP,
    sendPayload,
    startInstallation
  };
})();

// Auto-start when page loads
window.addEventListener('load', async () => {
  const params = new URLSearchParams(window.location.search);
  const pkgUrl = params.get('pkg');
  const filename = params.get('name');
  const metadata = params.get('metadata');
  
  if (pkgUrl && filename) {
    console.log('Auto-starting installation...');
    const success = await exploit.startInstallation(pkgUrl, filename, metadata);
    
    if (success) {
      document.getElementById('status').innerHTML = 
        '<div style="color: green; font-weight: bold;">✅ Installation started! Check your PS4 notifications.</div>';
    } else {
      document.getElementById('status').innerHTML = 
        '<div style="color: red; font-weight: bold;">❌ Installation failed. Try manual method.</div>';
    }
  }
});
`;

        return {
            statusCode: 200,
            headers: {
                'Access-Control-Allow-Origin': '*',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                success: true,
                metadata: metadata,
                jsPayload: jsPayload,
                directUrl: `${pkgUrl}?download=true`,
                installationUrl: `/install.html?pkg=${encodeURIComponent(pkgUrl)}&name=${encodeURIComponent(filename)}&metadata=${metadata}`,
                instructions: [
                    '1. Open this page on your PS4 browser',
                    '2. Click "Start Installation" button',
                    '3. The PS4 will download and install the package',
                    '4. Check your notifications for installation progress'
                ]
            })
        };

    } catch (error) {
        return {
            statusCode: 500,
            body: JSON.stringify({ error: error.message })
        };
    }
};